// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome');
const chromedriver = require('chromedriver');
const assert = require('assert')

describe('testeAcessarPaginasRestritasDESLOGADO', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.close();
  })
  it('testeAcessarPaginasRestritasusuarioCliente', async function() {
    await driver.get("http://localhost:3000/usuarioCliente")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritaseventos', async function() {
    await driver.get("http://localhost:3000/eventos")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritasusuarioEstabelecimento', async function() {
    await driver.get("http://localhost:3000/usuarioEstabelecimento")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritaseventoAtivos', async function() {
    await driver.get("http://localhost:3000/eventos/ativos")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritaseventosEncerrados', async function() {
    await driver.get("http://localhost:3000/eventos/encerrados")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritasagenda', async function() {
    await driver.get("http://localhost:3000/agenda")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('testeAcessarPaginasRestritashome', async function() {
    await driver.get("http://localhost:3000/home")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".fw-normal")).click()
    await driver.findElement(By.css(".fw-normal")).click()
    {
      const elements = await driver.findElements(By.css(".fw-normal"))
      assert(elements.length)
    }
    await driver.close()
  })
})
