// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testeAcessarPaginasRestritasLogadoContaComun', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.close();
  })
  it('testeAcessarPaginasRestritasLogadoContaComun', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.css("form > .mb-3:nth-child(1)")).click()
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.css(".lead")).click()
    {
      const elements = await driver.findElements(By.css(".lead"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagEventos', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.linkText("Eventos")).click()
    await driver.findElement(By.css(".lead:nth-child(2)")).click()
    {
      const elements = await driver.findElements(By.css(".lead:nth-child(2)"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagAgenda', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.linkText("Agenda")).click()
    await driver.findElement(By.css(".lead")).click()
    {
      const elements = await driver.findElements(By.css(".lead"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagHome', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.css(".bg-image")).click()
    await driver.findElement(By.css(".font-size60px")).click()
    {
      const elements = await driver.findElements(By.css(".font-size60px"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagEstabelecimento', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.css(".lead")).click()
    {
      const elements = await driver.findElements(By.css(".lead"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagEventosAtivos', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.css(".lead")).click()
    {
      const elements = await driver.findElements(By.css(".lead"))
      assert(elements.length)
    }
    await driver.close()
  });
  it('testeAcessarPaginasRestritasLogadoContaComunPagEventosEncerrados', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.id("floatingInput")).click()
    await driver.findElement(By.id("floatingInput")).sendKeys("pedro@gmail.com")
    await driver.findElement(By.id("floatingPassword")).click()
    await driver.findElement(By.id("floatingPassword")).sendKeys("123456")
    await driver.findElement(By.css(".w-100")).click()
    await driver.findElement(By.css(".lead")).click()
    {
      const elements = await driver.findElements(By.css(".lead"))
      assert(elements.length)
    }
    await driver.close()
  })
})
